name: mcafee_security_analyzer
description: "Professional Message Security Analyzer - Spam Detection & Threat Analysis"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Material Design
  cupertino_icons: ^1.0.8
  
  # Networking & HTTP
  http: ^1.2.2
  
  # Regular Expressions & Text Analysis
  string_validator: ^1.1.0
  
  # URL Validation & Security
  url_launcher: ^6.3.1
  validators: ^3.0.0
  
  # Cryptography & Hashing
  crypto: ^3.0.6
  
  # State Management
  provider: ^6.1.2
  
  # Local Storage & Persistence
  shared_preferences: ^2.3.4
  
  # Date & Time
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true